### PR TITLE
Wmmc88/hex tol test

### LINKED ISSUE #58: Hex Test Fit Part
A simple test part to verify printing tolerances for hex shaft in hex hole

### PR DESCRIPTION
**Pull request by wmmc88**
image

Same Pins (7.95mm diameter). Left hole starts with 0.01mm surface to surface clearance (7.97mm diameter hole). clearance steps up by 10 microns each hole. The last hole has 190 microns of clearance and is 8.33 mm diameter. 

^referring to circles but hex has same pattern

from previous testing, 200 microns of clearance was a very loose fit and 150 micron was interference(tho could have been due to print issues)

Closes #58

### CODE REVIEW

**Comment by wmmc88** [comment]
Waiting for petg to print and merge

**Review by matthew-reynolds — APPROVED** [review]
thank you kanye, very cool

**Comment by matthew-reynolds** [comment]
Closes #58

**Comment by wmmc88** [comment]
@matthew-reynolds as discussed, we "tight" fits of around 10 microns for hex and 30 microns for circle. can size slip and interference around that

**Review by matthew-reynolds — APPROVED** [review]
oops, didn't realize I needed to re-approve this mb

**Pull request merged**
