### PR TITLE
Zed bracket

### LINKED ISSUE #119: Zed bracket

### PR DESCRIPTION
**Pull request by matthew-reynolds**
Closes #119 

Points the camera directly horizontally.

image

### CODE REVIEW

**Review by wraftus — APPROVED** [review]
lgtm, are we worried about zed getting bonked if the dog walks into something?

**Comment by matthew-reynolds** [comment]
> lgtm, are we worried about zed getting bonked if the dog walks into something?

Don't think so, it's pretty protected by the motors
image

**Review by wmmc88 — COMMENTED** [review]
I would protect the zed more around the sides

**Comment by matthew-reynolds** [comment]
> I would protect the zed more around the sides

can you give a sketch

There isn't a ton of room to add more protection without getting in the way of the motors

**Comment by wmmc88** [comment]
> > I would protect the zed more around the sides
> 
> can you give a sketch
> 
> There isn't a ton of room to add more protection without getting in the way of the motors

image

also might help it from twisting

**Comment by matthew-reynolds** [comment]
> > > I would protect the zed more around the sides
> > 
> > 
> > can you give a sketch
> > There isn't a ton of room to add more protection without getting in the way of the motors
> 
> image
> 
> also might help it from twisting

Not gonna lie I have no idea what this sketch is showing lol

**Pull request merged**
