### PR TITLE
Motor dims

### PR DESCRIPTION
**Pull request by matthew-reynolds**
Updated M365 motor model to match real dimensions. (Screws aren't modeled but whatever everything else is). Most dims actually matched or were off by like 1mm, so pretty good eyeballing :) The motor model also has both the rotor and end caps trimmed down to the necessary diameter, and the end cap has air holes.

Stator, end-cap, and rotor+cable weights are specified, but will need to be re-weighed once we actually do the modifications. Other hardware (bearings, washer, nuts) just have weight calculated by volume based on 1045 steel. Screws are not included. I might go back and update these weights once we modify and measure the rotor and end cap.

image
image
image

The rotor output shaft is modified to fit the finalized motor dims and align the rotor and stator. Also it is made more printable. A groove in this part fits a ring, which interfaces with a chamfer on the motor rotor in order to centre the parts.

image
image
image

The motor module is updated to use the new motor and rotor shaft models. Casing dims do not change. Motor-to-casing clearance is 1.5mm on all sides.

image
image

image

### CODE REVIEW

**Review by wraftus — APPROVED** [review]
We may want to add a chamfer to the end of the hex shaft so it'll easier assembling it in the CAMs, but not a big deal.

**Comment by matthew-reynolds** [comment]
> We may want to add a chamfer to the end of the hex shaft so it'll easier assembling it in the CAMs, but not a big deal.

Good idea. I was thinking this in the shower this morning too. It would also help get the encoder on.

Follow-up.

**Comment by matthew-reynolds** [comment]
> Are we planning on keeping the nuts to constrain the one bearing on this shaft? did we need to print some spacer for that?

wdym? Does the last screenshot in the PR answer the question?

**Comment by wmmc88** [comment]
> 

oops i forgot the end was cut down

**Pull request merged**
