### PR TITLE
Fasten lever arm with end bolt

### PR DESCRIPTION
**Pull request by matthew-reynolds**
image

### CODE REVIEW

**Review by wmmc88 — COMMENTED** [review]
chamfer around the circle the screw is tightened down on would aid printing

**Comment by matthew-reynolds** [comment]
> chamfer around the circle the screw is tightened down on would aid printing(minor)

Done

image

**Comment by wmmc88** [comment]
oops i meant fillet

**Comment by matthew-reynolds** [comment]
> oops i meant fillet.. brain is a little fried

Fine either way though right? You just wanted something to make the overhang more gradual?

**Comment by wmmc88** [comment]
> > oops i meant fillet.. brain is a little fried
> 
> Fine either way though right? You just wanted something to make the overhang more gradual?

fillets are a little better cuz then there isnt a huge acceleration at the corners (could cause some artifacting)

**Comment by matthew-reynolds** [comment]
I don't really know what you mean by acceleration lol but I'm also smooth brained.

Anyways, replaced chamfer with fillet:

image

**Review by wmmc88 — APPROVED** [review]

**Pull request merged**
