### PR TITLE
Engrave cycloidal disc config

### PR DESCRIPTION
**Pull request by matthew-reynolds**
Engraved 1/4mm deep.

image
image

### CODE REVIEW

**Review by wmmc88 — APPROVED** [review]

**Comment by wmmc88** [comment]
How wide are the engravings. Wondering if maybe it wont show up nicely

**Comment by matthew-reynolds** [comment]
> How wide are the engravings. Wondering if maybe it wont show up nicely

5mm tall, ~4mm wide

**Comment by wmmc88** [comment]
Is this the only pr needed to close #34?

Another option in simple parts like this one is that I can print the letter in like PLA in a different colour. Sort of like this print:

Also the only thing that matters in the gearbox is that there's one of each, right? doesn't matter which goes where for it to mate?

**Comment by matthew-reynolds** [comment]
> Is this the only pr needed to close #34?

Yup, forgot to link it whoops

> Another option in simple parts like this one is that I can print the letter in like PLA in a different colour. Sort of like this print:

Missing pic? Also seems unnecessary tbh. We just need a tiny mark to make sure we have one of each

> Also the only thing that matters in the gearbox is that there's one of each, right? doesn't matter which goes where for it to mate?

That's right

**Review by wraftus — DISMISSED** [review]

**Comment by matthew-reynolds** [comment]
Whoops, dismissed reviews by enlargening the text to 8mm tall

@wmmc88 @wraftus

**Review by wmmc88 — APPROVED** [review]

**Pull request merged**
