### PR TITLE
Knee Belt & Pulleys

### PR DESCRIPTION
**Pull request by matthew-reynolds**
- Size belt for Omega HP 1224-8M-20 (https://www.mcmaster.com/7939K688/)
- Size pulleys for ~1.6:1 (63:39) ratio and maximize diameters to minimize tension in the belt. We're pushing the limits on the belt's loading capacity.
  - 39T was selected to maximize pulley dia without having to re-design the knee motor bracket.
  - 63T was selected to get ~1.55:1 ratio and to give a reasonable balance of reduced belt load without a stupidly large pulley.
- Add belt tensioner, re-using FRC bearings
- Add pulley & belt teeth (These don't mesh perfectly, so there's probably interference, but it is what it is. Also, the pulley profile may need slight adjustment once we have a belt in hand to test with)

image
image
image
image

### CODE REVIEW

**Comment by matthew-reynolds** [comment]
Dunno if the idlers should be crowned or not. I suspect probably yes, but currently they are drawn flat. Advantage to crowning is centering the belt, disadvantage is slightly harder to print and slightly more belt wear. We'll probably have to make then crowned in a follow-up.

**Comment by matthew-reynolds** [comment]
Also, if you're wondering why the idlers are so large, it's to avoid undue wear on the belt. The belt datasheet specs a max 60mm dia of backside idler (https://www.optibelt.com/fileadmin/pdf/datenblaetter/Technical-Data-Sheet-optibelt-OMEGA-HP-8M.pdf)

**Comment by wmmc88** [comment]
> Dunno if the idlers should be crowned or not. I suspect probably yes, but currently they are drawn flat. Advantage to crowning is centering the belt, disadvantage is slightly harder to print and slightly more belt wear. We'll probably have to make then crowned in a follow-up.

crowned sounds good

**Comment by wmmc88** [comment]
> Also, if you're wondering why the idlers are so large, it's to avoid undue wear on the belt. The belt datasheet specs a max 60mm dia of backside idler (https://www.optibelt.com/fileadmin/pdf/datenblaetter/Technical-Data-Sheet-optibelt-OMEGA-HP-8M.pdf)

gross

**Review by wmmc88 — APPROVED** [review]
So the idea is sliding it closer to the knee increases tension?

**Comment by matthew-reynolds** [comment]
> So the idea is sliding it closer to the knee increases tension?

Yep, that's right

**Comment by matthew-reynolds** [comment]
> > Dunno if the idlers should be crowned or not. I suspect probably yes, but currently they are drawn flat. Advantage to crowning is centering the belt, disadvantage is slightly harder to print and slightly more belt wear. We'll probably have to make then crowned in a follow-up.
> 
> crowned sounds good

ok. Will do in follow up.

**Pull request merged**
