### PR TITLE
Add a fixture for testing a full leg

### LINKED ISSUE #47: Design leg testing fixture

### PR DESCRIPTION
**Pull request by wraftus**
Fixture for testing and developing with a full leg. Is meant to work with the front right configuration.
image
closes #47

### CODE REVIEW

**Comment by matthew-reynolds** [comment]
Where's the tennis ball >:(

Also, how is the 8020 held in the 2x4s?

**Comment by wmmc88** [comment]
> Also, how is the 8020 held in the 2x4s?

ditto on this. but otherwise looks fine to me

**Comment by wraftus** [comment]
> Where's the tennis ball >:(
> 
> Also, how is the 8020 held in the 2x4s?

Forgot to add the fastener holes, but planned on using the same 1/4-20 blot + 8020 nut we use in the chassis. Home Depot's website doesn't say what bolts they carry, so if they don't have the right ones the EMS does so I'll pick them up there
image

**Comment by wraftus** [comment]
> > Also, how is the 8020 held in the 2x4s?
> 
> ditto on this. but otherwise looks fine to me.
> 
> a little worried with all the weight cantilevered on it. where does SW tell you the Cg of the rig is?

image
image
Solidwork's com doesn't seem to behave. I think it looks good from inspection lol, but the modules are chunky. We can extend the base beams if you're worried about it tipping

**Comment by wmmc88** [comment]
Discussed offline. Probs fine and will just put wright's on the base if needed

**Comment by matthew-reynolds** [comment]
Closes #47.

It would be cheaper to just sandwich the 8020 between wood screws, but then we might be a little bit of movement when we have sharp accelerations in the joints :'( I guess 1/4-20s will have to do.

Have you checked whether our 1" 1/4-20s are long enough to be used here without buying more wood? We'd have to counterbore the 2x4 a bit, but maybe that would work?

**Review by wmmc88 — APPROVED** [review]
I modified comment to say closes #47. looks good since you already built it lol. might mirror some suports on the non-supported sides later or weight down the supported sides significantly.

**Review by matthew-reynolds — APPROVED** [review]
> Have you checked whether our 1" 1/4-20s are long enough to be used here without buying more wood? We'd have to counterbore the 2x4 a bit, but maybe that would work?

This is the approach we went with.

**Pull request merged**
