### PR TITLE
Chassis

### PR DESCRIPTION
**Pull request by matthew-reynolds**
lol

image

### CODE REVIEW

**Comment by matthew-reynolds** [comment]
A bit less lol, but still lookin' jank

image

**Comment by matthew-reynolds** [comment]
TODO: 92949A443 too short for bat box?

**Comment by matthew-reynolds** [comment]
image
Getting close to ready to PR. Main outstanding task is plastic parts to retain battery.

TODO list:
 - ~Fix belts~
 - ~Add remaining fasteners to chassis~
 - Add plastic parts to fully constrain battery
 - Limit switch mounting???
 - Finalize pwr reg selection and draw it in + its mount
 - Maybe extend the Jetson bracket to give a spot to mount the CAN transceiver
 - If I'm feeling spicy, add cables. If I'm feeling less spicy, just draw them on in 2D
 
 Only the battery parts ought to be part of this PR. The rest can be subsequent PRs.

**Comment by matthew-reynolds** [comment]
## Full dog

dog

## Splay motor bracket
image
image

Mounts to chassis with 4x T-slot nut/bolts on the top and bottom. Second image shows section view through one of the T-slot bolts (highlighted). Easily slides off, for maintenance & transportation.

## Chassis
image
image
image
image

Chassis made from 1x1 T-slot extrusion for strength. 3rd image shows corner fasteners: 2 bolts into T-slot nuts, and 1 bolt into the end of the horizontal extrusion. 4th image shows central structure fasteners: 1 bolt into each end of each horizontal extrusion. All holes in 8020 are either 1/4" or 1/2", both because that matches the bolts used and because those are the sizes of drill bits I have.

## Battery Compartment
image
image
image
image

Weight of battery rests on center bottom beams. 4 printed parts retain the battery in X and Y. If we're worried about Z, we can slap on some ratchet straps or similar. The front/back printed part is shown in the 3rd image, while sides are shown in 4th. Printed parts are mounted using T-slot bolts/nuts, and have a 45deg chamfer to guide the battery into place. **NOTE: Need to actually measure the battery and adjust brackets before printing. Current battery dims are guesstimated from the manual & images**

## Breaker & Jetson mounts
image
image
image
image
image
image

Breaker is mounted to chassis with 4 T-slot bolts/nuts, and the breaker to the bracket using our standard M3 bolts+inserts, along with a printed washer (See pic 3).
Jetson is mounted to the chassis the same way, but with a corner cut out to not block the battery box beam bolt. Jetson is mounted to bracket by replacing the Jetson's feet with standoffs built into the bracket. Bolts thread into the Jetson from behind.

## ODrives & Bus Bars

image
image
image
image
image
image

ODrive panels mount to the chassis using 6 T-slot nuts/bolts (probably overkill lol). ODrives mount to the panel using standard M3 bolts+inserts, plus a printed spacer. Bus bars mount to the bottom of the panel, again using M3 bolts+inserts, and using the same washer as the breaker. Bus bars are separated by a plastic piece just for safety. There are 3 slots cut in the panel to pass cables from the bus bar up to the ODrives.

**Comment by wmmc88** [comment]
>  Current battery dims are guesstimated from the manual & images
Did u want to grab the measurements u want?

**Comment by wmmc88** [comment]
Is there a reasons we're drilling thru the 8020 instead of using a bolt head on the other side. Seems a lil dicey:
image

**Comment by wmmc88** [comment]
image
Looks like its lacking space for the power resistors

**Comment by wmmc88** [comment]
Very concerned about how exposed the jetson is:
image

**Comment by wmmc88** [comment]
Smth that doesn't matter too much is that the battery placement would be impractical in a real use situation (given a load will be sitting on a basket on top. Wonder if the chassis box could be tall enough for the battery to slide out one of the sides for swaps

**Comment by matthew-reynolds** [comment]
> > Current battery dims are guesstimated from the manual & images
> 
> Did u want to grab the measurements u want?

image
I think these, and then also the thickness of the black rubber base and top cap (kinda shitty pic mb):
image

> Is there a reasons we're drilling thru the 8020 instead of using a bolt head on the other side. Seems a lil dicey:

Bolt head on the other side? How would we tighten it? The "right" way is to buy brackets but they're stupid expensive lol

> Looks like its lacking space for the power resistors

Oh I thought we didn't need it anymore since we're doing regenerative breaking, but I suppose we still need one as a backup. Do we know the model/dims?

> Very concerned about how exposed the jetson is:

It's not as bad as it looks, since the splay motors stick out past it, but agreed it probably ought to have a printed casing. Added to the TODO list.

> Smth that doesn't matter too much is that the battery placement would be impractical in a real use situation

I think "impractical" is strong (Just have the basket lift off or flip up), but agreed that it's not ideal. But it's not sometihng we need to worry about for the prototype, and other approaches are more mechanically complex & expensive. Real thing could lide in the side, or load from the bottom. Worth mentioning in report perhaps

**Comment by wraftus** [comment]
> Bolt head on the other side? How would we tighten it? The "right" way is to buy brackets but they're stupid expensive lol
Couldn't we make our own brackets? Might be easier to get the machine shop to router us some or something instead of us milling all of them.

Also since we have free machine shop credits, would we be able to machine the battery holders and the odrive/jetson/breaker plates out of some plastic? material might be too expensive to make sense but would save a lot of print time and those should be easy machine jobs

**Comment by matthew-reynolds** [comment]
> Could we make our own brackets? Might be easier to get the machine shop to router us some or something instead of us milling all of the T-slots.

Oh I hadn't even considered using the mill for those holes lmao I was imagining drilling them by hand. Mill is a much better idea, we could actually get things somewhat precise lol.

tbh probably still cheaper & easier to just pop a few holes into the 8 pieces of extrusion than making brackets though. I dunno what advantage brackets really has.

**Comment by matthew-reynolds** [comment]
> Also since we have free machine shop credits, would we be able to machine the battery holders and the odrive/jetson/breaker plates out of some plastic? material might be too expensive to make sense but would save a lot of print time and those should be easy machine jobs

Good idea, we should see what material costs are like

**Comment by wraftus** [comment]
> Good idea, we should see what material costs are like

mm may not be worth it actually, did a quick look on McMaster-Carr and the EMS and plastic is expensive lol. They're pretty small parts so probably not worth it, but something we can keep in mind if printing time is uber tight

**Comment by wmmc88** [comment]
> > > Current battery dims are guesstimated from the manual & images
> > 
> > 
> > Did u want to grab the measurements u want?
> 
> image I think these, and then also the thickness of the black rubber base and top cap (kinda shitty pic mb): image

red: 223
yellow: 164
blue: 162
green: 100
2.25mm small lip
17.75mm rubber

> > Is there a reasons we're drilling thru the 8020 instead of using a bolt head on the other side. Seems a lil dicey:
> 
> Bolt head on the other side? How would we tighten it? The "right" way is to buy brackets but they're stupid expensive lol

Right... uh. just worried about it failing in that section. f e a?

> > Looks like its lacking space for the power resistors
> 
> Oh I thought we didn't need it anymore since we're doing regenerative breaking, but I suppose we still need one as a backup. Do we know the model/dims?

Regen braking doesnt preclude the use of power resisitors. Once we hit the max negative current threshold, the remaining energy is dissipated into the resistor. if there isn't a power resistor, then will hit a different threshold that will fault the odrive and cause it to cut power.

Was planning on using the default ones given for now and respec if we have issues based on our max decceleration.

> 
> > Smth that doesn't matter too much is that the battery placement would be impractical in a real use situation
> 
> I think "impractical" is strong (Just have the basket lift off or flip up), but agreed that it's not ideal. But it's not sometihng we need to worry about for the prototype, and other approaches are more mechanically complex & expensive. Real thing could lide in the side, or load from the bottom. Worth mentioning in report perhaps

I was thinking if ur mid job and u need to battery swap, you wouldn't want to load all your heavy cargo just to swap battery.

**Review by wmmc88 — APPROVED** [review]

**Comment by matthew-reynolds** [comment]
> red: 223
> yellow: 164
> blue: 162
> green: 100
> 2.25mm small lip
> 17.75mm rubber

ty. Can you also measure the rubber lip to the body? or is it the same as the metal lip at the top?

>> Do we know the model/dims?
> Was planning on using the default [dissipation resistors] given for now and respec if we have issues based on our max decceleration

Right but I dunno what the default is lol

>>> Smth that doesn't matter too much is that the battery placement would be impractical in a real use situation
>>
>> I think "impractical" is strong (Just have the basket lift off or flip up), but agreed that it's not ideal. But it's not sometihng we need to worry about for the prototype, and other approaches are more mechanically complex & expensive. Real thing could lide in the side, or load from the bottom. Worth mentioning in report perhaps
>
> I was thinking if ur mid job and u need to battery swap, you wouldn't want to load all your heavy cargo just to swap battery.

True true

**Comment by wmmc88** [comment]
how did u actually end up fixing the mates for the assembly?

**Comment by matthew-reynolds** [comment]
> how did u actually end up fixing the mates for the assembly?

The belt? I rebuilt the leg asm so that the belt was in approx the same position in each of the 4 configs so that the solver didn't freak out when solving simultaneous configs

**Pull request merged**
