### PR TITLE
Update chassis COTS components

### LINKED ISSUE #38: Model power regulator & mount

### LINKED ISSUE #41: Model ODrive dissipation resistors

### PR DESCRIPTION
**Pull request by matthew-reynolds**
- Updated battery dims, and (accordingly) battery brackets
 - Updated bus bar dims
 - Added ODrive brake resistors (Closes #41)
 - Added Jetson power regulator (Closes #38)
 
 Brake resistors can be seen here:
image
image

Jetson regulator can be seen here:
image
image

### CODE REVIEW

**Comment by wmmc88** [comment]
my god u actually modelled the whole brake resistor instead of just a box

**Comment by wmmc88** [comment]
Only thing i have concerns for is routing of the encoder cables. we should probably try to run them farther from the power lines and if its still bad, then buy some shielding

**Comment by matthew-reynolds** [comment]
> Only thing i have concerns for is routing of the encoder cables. we should probably try to run them farther from the power lines and if its still bad, then buy some shielding

Ye I agree

**Comment by wmmc88** [comment]
> > Only thing i have concerns for is routing of the encoder cables. we should probably try to run them farther from the power lines and if its still bad, then buy some shielding
> 
> Ye I agree

could we run the encoder cables seperate of the power ones and have them go under the chassis up a hole?

**Comment by matthew-reynolds** [comment]
> > > Only thing i have concerns for is routing of the encoder cables. we should probably try to run them farther from the power lines and if its still bad, then buy some shielding
> > 
> > 
> > Ye I agree
> 
> could we run the encoder cables seperate of the power ones and have them go under the chassis up a hole?

The bottom of the odrive panel is too full I think. tbh I think just running them straight across the top of the odrives, rather than off to the sides in the same bundles as the motor lines, would probably suffice.

**Review by wmmc88 — APPROVED** [review]

**Pull request merged**
