### PR TITLE
Use set-screws to hold 8020 in place.

### PR DESCRIPTION
**Pull request by matthew-reynolds**
Additionally, added a slot to facilitate assembly.

image
image
image

Also added a few fillets
image

### CODE REVIEW

**Comment by matthew-reynolds** [comment]
As before, we likely don't need 12 screws to hold the 8020 in place. But it's easier to model them in now and populate them as needed.

**Comment by wmmc88** [comment]
Wait.. so there's threaded inserts in the 3d printed part of each of the 12 screws and we're gonna use the screws as set screws? lmao

**Comment by matthew-reynolds** [comment]
> lmao

this isn't very constructive >:(

We should merge this since I have a few other PRs stacked on top of this. Adding a back wall for an end-bolt will be another PR

**Review by wmmc88 — APPROVED** [review]

**Review by wraftus — APPROVED** [review]
I've been kind of out of it for the discussions, but do we have a plan for how we're holding this thing down?

**Comment by wmmc88** [comment]
> I've been kind of out of it for the discussions, but do we have a plan for how we're holding this thing down?

clamp that we must procure

**Comment by matthew-reynolds** [comment]
> do we have a plan for how we're holding this thing down?

Ye just clamp it to a table. That flat bit between on the right of the last image is the clamping surface

**Pull request merged**
