### PR TITLE
Prelim motor module (No gearing)

### PR DESCRIPTION
**Pull request by matthew-reynolds**
Modeled the "motor" half of the motor module, including encoder. The gearbox half is still needed (@wraftus).

image

To make the print easier, we might consider splitting the casing in half, and then fastening or, more likely, gluing the two halves together. If we do this, we should add locating features to the split surface, so that the orientation of the two halves of the motor casing is maintained.

image

### CODE REVIEW

**Comment by wmmc88** [comment]
Why wouldn't we just print it with the left or right face being the base? I guess the constraint would just be max z height but my print has a pretty tall volume

**Comment by matthew-reynolds** [comment]
> Why wouldn't we just print it with the left or right face being the base?

Because then we have mondo overhang of the middle bit

```
|   |
|   |   <- gearbox
|---|
|   |   <- motor
|   |
```

**Comment by wmmc88** [comment]
Over hand is no problemo. Support + dissolvable interface layer. IDEX printing :)))))

**Comment by matthew-reynolds** [comment]
> Over hang is no problemo. Support + dissolvable interface layer. IDEX printing :)))))

Okie dokie

**Comment by matthew-reynolds** [comment]
We will also need to add a hole for the encoder cable at some point. Not sure if we want that to come out radially or axially. Axial risks getting caught by the motor and tearing, but means the cables come out closer to the motor cables. Radial means we'd need to run the cables along the outside of the motor module. No biggie either way.

**Comment by wmmc88** [comment]
My vote is axially. Can probably 3d print a channel for the wires

**Comment by matthew-reynolds** [comment]
Updated screenshots:

image
image

Top-down section view:
image


Side section view:
image

**Comment by matthew-reynolds** [comment]
Still to do:
 - Add cycloidal disc
 - Add ring gear geometry
 - Add output plate bushings & pins
 
 I think this is ready to merge, those changes can be in another PR by @wraftus.

**Review by wmmc88 — APPROVED** [review]
looks solid to me. idk if the others have opnions here (smh they're not in the github org yet so i can't tag them)

**Comment by matthew-reynolds** [comment]
> idk if the others have opnions here

I'm going to merge. Further revisions can just happen in further PRs

**Pull request merged**
